before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: wsVHbuuguAcDxTqYfCOVl07UwQ3pdp5BdBtYOJghFA0tCQ50cHci+6b+jstvDxljRQypObvTxyJpsLJTJLTvaxRrxiMGLRulF3F7Qq/PyHx3Bxvf0RBWj4Nfph4dsFECFs8Ip+VpS8OvA8ICR0aDa8oVHcUBSHqgpigZvINeXEsZy4/WBUwnBVTKjCY9yl0hOhYq2+RJmAciRFmdrFrSyk0jjEiOvCCWwtMy2xknCWnDHzZS34mqT80/N6vBmUxdxaxsIBPDmI00uRj5nJWU+O2t+vflcS/Ve0jpffUvk1UDMp2kMXE8WTf/fFEvAoC6BfFEBPMXLXdLHvPovgxp0eVozaZVOWX0SsSlQsNB1o+8YiYoodQETGFWihmZBxu03KvfNPBIlDNEktYiVTJN34E7FbX1JJ7tXZbpIUvU0ClT33AINVHlJXCqHrlrgzfAv0/45ltJJ7GYEjtRQPEFxGkQZR41iGqOEolhODnotyAjDXpcUi+g5MpLVxHehHlgH4fLqJS4EOPpZlKgEdjSN3bbin4cdJb+6arwJu/tuVqDepX1Pe0pnSog5z5vkYPSzMC3kwp+rnBnAE1UqIeTTVrSd1NL9aebHIe1/N1rPjqmFFTNAY4/aigWnYJPwTTTS5BDNVlauF42JLmzhytINpq5sN+w7sPi/Zzlmp15W3Y= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
